import manifest from "../../db/seed/media.json";
import local from "./media-local.json";

/**
 * Real crests and real photography, resolved by name.
 *
 * The manifest is generated by `python -m gamesenze.jobs.resolve_media`, which
 * searches TheSportsDB for each canonical club name and accepts only a result
 * that agrees it has that name. The matched name is kept in the manifest, so
 * every crest on the site can be traced back to the row it came from.
 *
 * A club we could not confirm has no entry and falls back to its monogram.
 * That is deliberate: putting Real Madrid's crest on Real Sociedad because it
 * was the first search hit is worse than showing initials.
 */

export type TeamMedia = {
  canonical: string;
  badge: string;
  banner?: string | null;
  fanart?: string[];
  stadium?: string | null;
  matched?: string;
};

export type CompetitionMedia = {
  key: string;
  badge?: string | null;
  banner?: string | null;
  logo?: string | null;
  fanart?: string[];
  matched?: string;
};

const TEAMS = (manifest as { teams: Record<string, TeamMedia> }).teams ?? {};
const COMPS = (manifest as { competitions: Record<string, CompetitionMedia> }).competitions ?? {};

/**
 * The files we carry ourselves, written by `fetch_media`.
 *
 * A crest served from someone else's CDN is a crest that disappears when they
 * have a bad day or when the reader is behind a restrictive network. These are
 * resized WebP copies in our own asset folder, so the board renders with no
 * third-party request at all. The remote URL stays as a fallback for anything
 * not yet pulled down.
 */
const LOCAL = local as {
  crests: Record<string, string>;
  competitions: Record<string, { badge?: string; photo?: string }>;
};

export function teamMedia(name: string | null | undefined): TeamMedia | null {
  if (!name) return null;
  const row = TEAMS[name];
  const localCrest = LOCAL.crests[name];
  if (!row && !localCrest) return null;
  return { ...(row ?? { canonical: name, badge: "" }), badge: localCrest ?? row?.badge ?? "" };
}

export function competitionMedia(key: string | null | undefined): CompetitionMedia | null {
  if (!key) return null;
  const row = COMPS[key];
  const l = LOCAL.competitions[key];
  if (!row && !l) return null;
  return { ...(row ?? { key }), badge: l?.badge ?? row?.badge ?? null };
}

/**
 * A photograph for a fixture.
 *
 * Club fanart lives on the vendor's CDN and is not carried locally: four
 * frames for each of 156 clubs is two orders of magnitude more than the
 * competition set, for imagery a reader sees one of at a time. So the
 * competition's own photograph is the first choice, which is both local and
 * the right picture anyway: a Champions League night should look like a
 * Champions League night.
 *
 * `index` lets several fixtures on one page draw different remote frames
 * rather than repeating one image down the board, where those are available.
 */
export function fixturePhoto(
  home: string | null | undefined,
  away: string | null | undefined,
  index = 0,
  competitionKey?: string | null,
): string | null {
  const local = competitionKey ? LOCAL.competitions[competitionKey]?.photo : null;
  if (local) return local;
  const pool = [
    ...(teamMedia(home)?.fanart ?? []),
    ...(teamMedia(away)?.fanart ?? []),
  ].filter(Boolean);
  if (pool.length) return pool[index % pool.length];
  return teamMedia(home)?.banner ?? teamMedia(away)?.banner ?? null;
}

export function competitionPhoto(key: string | null | undefined): string | null {
  if (!key) return null;
  const localPhoto = LOCAL.competitions[key]?.photo;
  if (localPhoto) return localPhoto;
  const m = competitionMedia(key);
  return m?.fanart?.[0] ?? m?.banner ?? null;
}

export const mediaCoverage = {
  teams: Object.keys(TEAMS).length,
  competitions: Object.keys(COMPS).length,
  localCrests: Object.keys(LOCAL.crests).length,
  localPhotos: Object.values(LOCAL.competitions).filter((c) => c.photo).length,
};
